server:
  port: 8080

spring:
  application:
    name: order
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}-${spring.application.instance_id}:${server.port}