server:
  port: ${SERVICE_PORT:8080}

spring:
  application:
    name: order-${PARTITION_ID:0}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    async:
      request-timeout: -1

PARTITION: ${PARTITION_ID:0}
NUMSTOCK: 2
NUMPAYMENT: 2
NUMORDER: 2