server:
  port: ${SERVICE_PORT:8080}

spring:
  application:
    name: order-${PARTITION_ID:0}

eureka:
  instance:
    ##hostname: ${hostName} # ####
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int}
  client:
    ##fetch-registry: true # ####
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:localhost} #http://${EUREKA_SERVER:localhost}:8761/eureka

PARTITION: ${PARTITION_ID:0}
BOOTSTRAP_SERVERS: ${KAFKA_SERVERS_CSL:localhost}:9092
