FROM maven:3.6.3-openjdk-17-slim as builder

WORKDIR /srv

COPY ./payment /srv/payment
COPY ./stock /srv/stock
COPY ./order /srv/order
COPY ./paymentwrapper /srv/paymentwrapper
COPY ./stockwrapper /srv/stockwrapper
COPY ./orderwrapper /srv/orderwrapper
COPY ./eureka /srv/eureka
COPY ./pom.xml /srv

RUN mvn clean package spring-boot:repackage

FROM maven:3.6.3-openjdk-17-slim

COPY --from=builder /srv/order/target/order-1.0-SNAPSHOT.jar /srv/order/target/order-1.0-SNAPSHOT.jar

CMD ["java", "-jar", "/srv/order/target/order-1.0-SNAPSHOT.jar"]
