version: '3'

services:

  payment-db:
    container_name: payment-db
    image: postgres
    environment:
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpwd
      POSTGRES_DB: paymentdb
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - payment-db
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - payment-db
    restart: unless-stopped

#  customer:
#    image: amigoscode/customer:latest
#    container_name: customer
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#      - payment-db
#    depends_on:
#      - zipkin
#      - postgres
#      - rabbitmq

networks:
  payment-db:
    driver: bridge
  spring:
    driver: bridge

volumes:
  payment-db-data:
  pgadmin: