version: '3'

services:

  order:
    build:
      context: .
      dockerfile: Dockerfile-order
    ports:
      - "8082:8080"
    depends_on:
      - order-db

  order-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    volumes:
      - order-db-data:/var/lib/postgresql/data

  payment:
    build:
      context: .
      dockerfile: Dockerfile-payment
    ports:
      - "8080:8080"
    depends_on:
      - payment-db

  payment-db:
    image: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpwd
      POSTGRES_DB: pgdb
    volumes:
      - payment-db-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

  stock:
    build:
      context: .
      dockerfile: Dockerfile-stock
    ports:
      - "8081:8081"
    depends_on:
      - stock-db

  stock-db:
    image: postgres
    environment:
      POSTGRES_USER: wdm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock
    volumes:
      - stock-db-data:/var/lib/postgresql/data

# pgadmin to inspect the dbs
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@example.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    restart: unless-stopped

volumes:
  order-db-data:
  payment-db-data:
  stock-db-data:
  #pgadmin:
