apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  rules:
    - http:
        paths:
          - path: /orders/
            pathType: Prefix
            backend:
              service:
                name: orderwrapper
                port:
                  number: 80
          - path: /stock/
            pathType: Prefix
            backend:
              service:
                name: stockwrapper
                port:
                  number: 80
          - path: /payment/
            pathType: Prefix
            backend:
              service:
                name: paymentwrapper
                port:
                  number: 80
