apiVersion: v1
kind: Service
metadata:
  name: orderwrapper
spec:
  type: NodePort
  selector:
    component: orderwrapper
  ports:
    - port: 80
      name: http
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderwrapper
spec:
  replicas: 2
  selector:
    matchLabels:
      component: orderwrapper
  template:
    metadata:
      labels:
        component: orderwrapper
    spec:
      containers:
        - name: orderwrapper
          image: docker.io/ngavalas/orderwrapper:latest
          env:
            - name: SERVICE_PORT
              value: "80"
          imagePullPolicy: Always
          command: ["java"]
          args: ["-jar", "/srv/orderwrapper/target/orderwrapper-1.0-SNAPSHOT.jar"]
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /orders
              port: 80
          livenessProbe:
            httpGet:
              path: /orders
              port: 80
