apiVersion: v1
kind: Service
metadata:
  name: order-0
spec:
  type: ClusterIP
  selector:
    component: order-0
  ports:
    - port: 8080
      name: http
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-0
spec:
  replicas: 2
  selector:
    matchLabels:
      component: order-0
  serviceName: "order-0"
  template:
    metadata:
      labels:
        component: order-0
    spec:
      containers:
        - name: order-0
          image: docker.io/ngavalas/order:latest
          env:
            - name: POSTGRES_USER
              value: pguser
            - name: POSTGRES_PASSWORD
              value: pgpassword
            - name: POSTGRES_DB
              value: pgdb
            - name: POSTGRES_HOST
              value: order-db-0-postgresql-ha-pgpool
            - name: SERVICE_PORT
              value: "8080"
            - name: KAFKA_SERVERS_CSL
              value: kafka
            - name: PARTITION_ID
              value: "0"
          imagePullPolicy: Always
          command: ["java"]
          args: ["-jar", "/srv/order/target/order-1.0-SNAPSHOT.jar"]
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: order-1
spec:
  type: ClusterIP
  selector:
    component: order-1
  ports:
    - port: 8080
      name: http
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-1
spec:
  replicas: 2
  selector:
    matchLabels:
      component: order-1
  serviceName: "order-1"
  template:
    metadata:
      labels:
        component: order-1
    spec:
      containers:
        - name: order-1
          image: docker.io/ngavalas/order:latest
          env:
            - name: POSTGRES_USER
              value: pguser
            - name: POSTGRES_PASSWORD
              value: pgpassword
            - name: POSTGRES_DB
              value: pgdb
            - name: POSTGRES_HOST
              value: order-db-1-postgresql-ha-pgpool
            - name: SERVICE_PORT
              value: "8080"
            - name: KAFKA_SERVERS_CSL
              value: kafka
            - name: PARTITION_ID
              value: "1"
          imagePullPolicy: Always
          command: ["java"]
          args: ["-jar", "/srv/order/target/order-1.0-SNAPSHOT.jar"]
          ports:
            - containerPort: 8080
