apiVersion: v1
kind: Service
metadata:
  name: paymentwrapper
spec:
  type: NodePort
  selector:
    component: paymentwrapper
  ports:
    - port: 80
      name: http
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentwrapper
spec:
  replicas: 2
  selector:
    matchLabels:
      component: paymentwrapper
  template:
    metadata:
      labels:
        component: paymentwrapper
    spec:
      containers:
        - name: paymentwrapper
          image: docker.io/ngavalas/paymentwrapper:latest
          env:
            - name: SERVICE_PORT
              value: "80"
          imagePullPolicy: Always
          command: ["java"]
          args: ["-jar", "/srv/paymentwrapper/target/paymentwrapper-1.0-SNAPSHOT.jar"]
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /payment/health
              port: 80
          livenessProbe:
            httpGet:
              path: /payment/health
              port: 80
