apiVersion: v1
kind: Service
metadata:
  name: stockwrapper
spec:
  type: NodePort
  selector:
    component: stockwrapper
  ports:
    - port: 8080
      name: http
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockwrapper
spec:
  replicas: 2
  selector:
    matchLabels:
      component: stockwrapper
  template:
    metadata:
      labels:
        component: stockwrapper
    spec:
      containers:
        - name: stockwrapper
          image: docker.io/ngavalas/stockwrapper:latest
          env:
            - name: SERVICE_PORT
              value: "8080"
          imagePullPolicy: Always
          command: ["java"]
          args: ["-jar", "/srv/stockwrapper/target/stockwrapper-1.0-SNAPSHOT.jar"]
          ports:
            - containerPort: 8080
