apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    component: payment
  ports:
    - port: 8080
      name: http
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: payment
  template:
    metadata:
      labels:
        component: payment
    spec:
      containers:
        - name: payment
          image: payment:latest
          env:
            - name: POSTGRES_USER
              value: pguser
            - name: POSTGRES_PASSWORD
              value: pgpassword
            - name: POSTGRES_DB
              value: pgdb
            - name: POSTGRES_HOST
              value: payment-db-postgresql-ha-pgpool
          imagePullPolicy: Never
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: ["java"]
          args: ["-jar", "/srv/payment/target/payment-1.0-SNAPSHOT.jar"]
          ports:
            - containerPort: 8080
