spring:
  application:
    name: payments-wrapper

server:
  port: ${SERVICE_PORT:8082}
  servlet:
    context-path: /payment
partitions: 2
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:localhost} # http://${EUREKA_SERVER:localhost}:8761/eureka
