spring:
  application:
    name: stocks-wrapper

server:
  port: ${SERVICE_PORT:8083}
  servlet:
    context-path: /stock
partitions: 2
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:localhost} #http://${EUREKA_SERVER:localhost}:8761/eureka
