server:
  port: 8080

spring:
  application:
    name: payment
  datasource:
    username: 'pguser'
    password: 'pgpwd'
    url: jdbc:postgresql://payment-db:5432/pgdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
