server:
  port: ${SERVICE_PORT:8081}

spring:
  application:
    name: payment
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}-${spring.application.instance_id}:${server.port}
