server:
  port: ${SERVICE_PORT:8081}

spring:
  application:
    name: payment-${PARTITION_ID:0}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:localhost} #http://${EUREKA_SERVER:localhost}:8761/eureka
