server:
  port: 8081

spring:
  application:
    name: payment
  datasource:
    username: 'paymentuser'
    password: 'paymentpwd'
    url: jdbc:postgresql://localhost:5432/paymentdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
