server:
  port: ${SERVICE_PORT:8080}

spring:
  application:
    name: payment
  datasource:
    username: ${POSTGRES_USER:pguser}
    password: ${POSTGRES_PASSWORD:pgpwd}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pgdb}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
