server:
  port: ${SERVICE_PORT:8081}
spring:
  application:
    name: stock
  datasource:
    password: ${POSTGRES_PASSWORD:password}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:stock}
    username: ${POSTGRES_USER:wdm}
  jpa:

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
