server:
  port: 8081
spring:
  application:
    name: stock
  datasource:
    password: password
    url: jdbc:postgresql://stock-db:5432/stock
    username: wdm
  jpa:

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
