server:
  port: 8084
spring:
  application:
    name: stock
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/stock
    username: postgres
  jpa:

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
